# Build Ubuntu Base Image
FROM ubuntu:latest

# For now...
MAINTAINER Alexander Senf <asenf@ebi.ac.uk>

# ROOT to set up the image
USER root

# Add a user and group first to make sure their IDs get assigned consistently, regardless of whatever dependencies get added
#RUN groupadd -r ega && useradd -r -g ega ega

# Dirs in Docker FS
#RUN mkdir /docker-entrypoint-initdb.d

# Suppress unnecesary warning messages
RUN echo 'debconf debconf/frontend select Noninteractive' | debconf-set-selections

# Enable addition of Repositories in Ubuntu
RUN apt-get update -y
RUN apt-get install -y software-properties-common python-software-properties

# Update Image, and Install Java 8 & Monit
RUN add-apt-repository ppa:openjdk-r/ppa
RUN apt-get -y update
RUN apt-get -y install openjdk-8-jdk
RUN apt-get -y install git
RUN apt-get -y install maven
RUN apt -y upgrade

